/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: "category",
      label: "說明",
      items: [
        {
          type: "autogenerated",
          dirName: "overview",
        },
      ],
    },
  ],
  component: [
    {
      type: "category",
      label: "GSAP",
      items: [
        {
          type: "autogenerated",
          dirName: "gsap",
        },
      ],
    },
  ],
};

module.exports = sidebars;
